### ISSUE TITLE
Eschecs docked

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#37]
Hello Roland.
Here video of Eschecs docked in action:
[eschecs_dock.mp4.zip](https://github.com/rchastain/eschecs/files/4068781/eschecs_dock.mp4.zip)

And here the msegui source:
[eschecs_mse.zip](https://github.com/rchastain/eschecs/files/4069270/eschecs_mse.zip)

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Very nice. Thank you ! I like the idea of the captured pieces, and also the idea of the time for each player. Maybe we could add the logo for each player (in case the player is an engine) ?

For my part, I am making improvements to the game manager. I made a command line version of Eschecs. I will send it to you soon.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.
This is a demo to show how docking works.
But of course nothing is working yet and the pieces-time form has to be more developed, like you proposed.

For the engine stuffs, your favorite method will be: **tboardfo.cellev(...)**
This is executed when something is done with the cells of the board.
Martin did prepare the work but, for example, the movements permitted for pieces has to be completed and, of course, the chess-engine has to be linked.

Fre;D

**Comment by fredvs** [comment]
> Maybe we could add the logo for each player

Yep, great idea.
By the way, would it be possible to make play 2 different chess engines, one against the other?

That would be a kind of movie...

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.

I would propose also a "Play Log" dock-form.
It may contain a grid of the log of each move:
(of course it may have images in the cells).
Something like your great ENGINES.md:

```
Number_Color_Piece_From___To___Result___Time____Engine

1   |  W  |  P  |  E2 |  E4 |         | 03:36 | Me
2   |  B  |  P  |  E7 |  E5 |         | 00:01 | Moustique
...
13  |  W  |  N  |  F3  | F5 | Kill BQ | 48:37 | Me

```
Fre;D

**Comment by rchastain** [comment]
> This is a demo to show how docking works.

Yes, it's how I understood it.

> Martin did prepare the work but, for example, the movements permitted for pieces has to be completed and, of course, the chess-engine has to be linked.

Yes. I think that, if we want to do good work, we should do things step by step, as Martin did for the elevator example. We could do by the same occasion a collection of examples for MSEgui.
I am not very satisfied of the main program of Eschecs 5. The code is so complicated that I don't understand myself how it works, and that I couldn't modify it without introducing bugs. This is what I would like to avoid with the new version.

> By the way, would it be possible to make play 2 different chess engines, one against the other?

Yes, it is possible, but IMHO it has to be developed and tuned separately. That's why I think that it would be good to start Eschecs 6 as a console application, and when we see that all work perfectly, we give a GUI to the program (the GUI which will have also been developed separately).
I would like to add to new features to the program. Time management, XBoard protocol support, chess variants support (Capablanca, Capablanca random), PGN support...

Very glad to work with you on this project.

**Comment by rchastain** [comment]
Your play log form is a good idea. The PGN standard would be perfect for that.

**Comment by rchastain** [comment]
So (to say all what I have in mind), if you agree with my idea of a collection of little separated examples, we could create a new repository for that. And also a new repository for the chess Pascal library. We could even choose a new name for the project. Why not MSEchess?

**Comment by fredvs** [comment]
> So (to say all what I have in mind), if you agree with my idea of a collection of little separated examples, we could create a new repository for that. And also a new repository for the chess Pascal library. We could even choose a new name for the project. Why not MSEchess?

Excellent!

Ok, I wait for your https://github.com/rchastain/MSEschecs/

Fre;D

**Comment by fredvs** [comment]
Note that I have zero skin about chess engine and how it works.
I have to study your code in your fpGUI_Eschecs to understand (but sadly I dont have time to jump into this at the moment).

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

What do you think of this?

https://github.com/mse-org/msechess

Don't lose your time to study Eschecs code. It's too complicated, because the interesting code is scattered in GUI methods. I will make some simple demos in text mode which will make things easier to understand.

Regards.

Roland

**Comment by rchastain** [comment]
I hesitate between rchastain/msechess and mse-org/msechess. Please let me know what you think of it. Maybe I should ask the question to Graeme too.

Regards.

**Comment by rchastain** [comment]
By the way, concerning your demo, it isn't really important now (since it's just a demo), but I think that we shouldn't mix "pixel" style and "anti-aliased" style. Your hatch squares are good for the Fritz chess pieces set, which was used in previous versions of Eschecs. I removed it because it was too complicated to manage different styles of pictures. Moreover, the pieces of the Fritz set have a white line around the piece, so that the black lines of the square don't touch the piece (which isn't pretty).
Since you use anti-aliased pieces, it would be better, IMHO, to use colored squares (light gray and dark gray, or white and blue, and so on), or textures (wood, marble).

**Comment by fredvs** [comment]
Hello Roland.

> I hesitate between rchastain/msechess and mse-org/msechess.

Hum, imho, Eschecs is your creation, that exists with fpGUI and soon with msegui widgetsets.
So, it should be in rchastain github repository.

Also the msegui version of Eschecs will not be "pure" mse, it will not use the mse status file but the one from fpGUI.  
The same for running the chess-engine, I propose to not use mseTprocess but the standard Tprocess from fpc.
This because there are some limitation on mseTprocess (can not stop a running process).

I did have the same hesitation with ideU, should it be part of mse-org, like mseide?

But, like for MSEschecs, ideU is not "pure msegui", it uses also no mse components.
I asked it to Graeme and he agrees with this.

> but I think that we shouldn't mix "pixel" style and "anti-aliased" style. 

Not sure to understand, could you give a example of both style?

Fre;D

**Comment by fredvs** [comment]
> hatch squares 

![MSEshecs_hatch](https://user-images.githubusercontent.com/3421249/72623873-2f2a0b80-3946-11ea-8713-48579fd7c8b0.png)

Fre;D

**Comment by fredvs** [comment]
> Your hatch squares

I do not have the honor to be the owner of that hatch squares.
It is Martin code, I only adapt it for live size-changing.

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.

> I hesitate between rchastain/msechess and mse-org/msechess. 

In /mseuniverse/samples/widgets/grids/chessboard/main.pas

Here the first lines of main.pas:

```
unit main;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}
{The example is based on eschecs
http://www.eschecs.fr/
from Roland Chastain
}
interface
```

So it seems that for Martin, the root is eschecs http://www.eschecs.fr/
from Roland Chastain.

**Comment by rchastain** [comment]
Hello Fred! Thank you for your messages. I will follow your advice and create a new repository on my domain.

Your demo is very impressive.

We have time to talk about details. But just have a look to this screenshot. This is what I call pixel style pieces. And you can notice that the lines don't touch the pieces.

![eschecs400original](https://user-images.githubusercontent.com/13957204/72626524-2c7de500-394b-11ea-85e1-fa7facf4b61f.png)

**Comment by fredvs** [comment]
> And you can notice that the lines don't touch the pieces.

Ha, yes, indeed, how do you get this?
With BGRabitmap?

Here the result without that feature, imho, it is not shocking:
![eschecsmsehatch](https://user-images.githubusercontent.com/3421249/72627846-74057080-394d-11ea-8cb4-4c30663b3151.png)

Fre;D

**Comment by rchastain** [comment]
I get this result because my pieces are surrounded by a white line, which overwrites the lines of the background.

![bb](https://user-images.githubusercontent.com/13957204/72630008-bd57bf00-3951-11ea-844e-c112399e738d.png)

The blue color was replaced at runtime by transparent color.

Concerning the screenshot that you posted, of course I wouldn't say it is shocking, but IMHO it isn't very nice. Look for example at the black bishop on the black square. You see how the cross looks? Compare with the same bishop on my screenshot.

I have to go. Thank you very much for your involvement in that project. We will make  great things in 2020.

Have a good night!

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

OK, I get it.
First I did convert the Fritz 40 bmp images to png format, added a alpha channel and assigned the blue background as alpha.

And msegui deals perfectly with it:

- With frame color set to white:

![friz40eschecs](https://user-images.githubusercontent.com/3421249/72645998-47654f00-3975-11ea-8e00-c474a3020cef.png)

- With frame color set to yellow:

![friz40yelloweschecs](https://user-images.githubusercontent.com/3421249/72648269-f0627880-397a-11ea-9cee-aed9863ac23a.png)


And here the Fritz converted images:

[fritz40png_yellowframe.zip](https://github.com/rchastain/eschecs/files/4079138/fritz40png_yellowframe.zip)

[fritz40png_whiteframe.zip](https://github.com/rchastain/eschecs/files/4079137/fritz40png_whiteframe.zip)

Good night!

Fre;D

**Comment by fredvs** [comment]
Just before to sleep.
I have to admit that I did not really get the problem.
Do you mean that it would be better to have a outline for each piece of font?

If it is the case, it is extremely simple to do it with Gimp, it takes less than 10 seconds for each piece.
But, yes, it needs lot of seconds if you want to do it for each size and each font.

But it is doable.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! Well done. Thank you for the pictures.

To answer your question, I believe 1° that the "Fritz board" (black and white pixels, without antialiasing), is good only for the Fritz pieces (black and white pixels, without antialiasing), and that the Fritz pieces look perfect only with the Fritz board. In some previous versions of Eschecs, the user could use the Fritz pieces with all the board styles, and some combinations didn't look very nice (in my opinion). That's why I had created (maybe you remember) some predefined combinations, but finally I found that it was too complicated to manage.

2° I believe, after having spent many hours on these problems, that it is too complicated to manage in the same application two different graphic style (on one hand, pure black and white style, without antialiasing, on the other hand coloured or textured board and pieces with antialiasing). That's why the latest version of Eschecs no longer uses the Fritz set (that I like however). For example, if for any reason you need to resize your pieces, with the antialiased pieces (Alpha, Mark...) it isn't a problem. But with the Fritz pieces, it is a problem. If you resize them, they will look ugly. What happens if the user selects the Fritz font and want a bigger board?

Sorry for that too long message. Have a nice day Fred!

Regards.

Roland

**Comment by rchastain** [comment]
So, if we want to use hatch squares (which is nice, indeed) with anti-aliased pieces, I suggest that we use anti-aliased hatch, and that we find a method to avoid contact between lines and pieces, like on this picture. But it could be complicated to do. The trick of the white line will work only on a white background...
![image](https://user-images.githubusercontent.com/13957204/72658768-093c4f80-39b6-11ea-841f-10ab25cadc28.png)

**Comment by rchastain** [comment]
You "play log" form looks very nice, but maybe it would be more appropriated as "about engines" form. This was, I believe, your first idea:

> Something like your great ENGINES.md

For the log of the game, a memo with a PGN text would be more convenient, and more appreciated by chess players (IMHO).

**Comment by fredvs** [comment]
Hello Roland.

> But with the Fritz pieces, it is a problem. If you resize them, they will look ugly.
> What happens if the user selects the Fritz font and want a bigger board?

Not sure to understand.
Are you saying that with Fritz font, there is only one size and each resize is a stretch from the original size?
Why dont have like other fonts, directories for each size and so set hardcoded the outline of each picture of 1 pixel ?

> For the log of the game, a memo with a PGN text would be more convenient, and more appreciated by chess players (IMHO).

Are you talking about the grid of the log-form that you prefer to be a simple memo?
OK, but you will loose lot of flexibility if it is a simple memo vs a grid.

If you want, the grid may looks as a memo, without grid-lines.

[EDIT] I agree that the logo of engine is maybe too much in the log-grid, the text-name would be enough.  And of course, with the "official" chess layout-words.

Fre;D

**Comment by fredvs** [comment]
> that we find a method to avoid contact between lines and pieces, like on this picture.

Ho, that is something for BGRAbitmap, at first view it seems not so easy to do by code.
By the way, do you have news about  BGRAbitmap + MSE?

Fre;D

**Comment by fredvs** [comment]
About the log-player form.
If I prefer a grid it is, for example, if in the captured-form the one clicks on a captured piece, it can jump in the log-player-grid and show the row when it was captured.

Fre;D

**Comment by fredvs** [comment]
> that it is too complicated to manage in the same application two different graphic style

Imho, the taste of people may highly differ.
It is like colors, I like green, other people prefers blue.

Ugly things for you may seem beautiful for others.

I propose to give, by default, the style that you prefer, with font, size, texture that you like.
Now if people prefer pink texture with hatch with font without white frame, if they are happy with it, why not?

If there is live changing, it is not boring, people may try it directly.

So to resume, maybe let give all the options to people, even if you dont like it.

My 1 ECO, of course.

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Thank you for your messages. We have time to think and talk about all that. I have to improve the chess library which makes Eschecs work, and I also have to start to learn MSEgui. 

This week I started to work on new chess pieces. I will show you the result soon.

Thank you for your ECO, even if I am a little sad (as you imagine) to see the _franc_ disappear. :)

Regards.

Roland

**Comment by rchastain** [comment]
> By the way, do you have news about BGRAbitmap + MSE?

No. But I wonder if we really need BGRABitmap in the application. Maybe the creation of graphics could be made separately?

Regards.

Roland

**Comment by fredvs** [comment]
> > By the way, do you have news about BGRAbitmap + MSE?
> 
> No. But I wonder if we really need BGRABitmap in the application. Maybe the creation of graphics could be made separately?
> 
> Regards.
> 
> Roland

Yes, at the moment I do not see the need of BGRABitmap, msegui does perfectly the work.

Have a perfect we.

Fre;D

**Comment by fredvs** [comment]
> Thank you for your ECO, even if I am a little sad (as you imagine) to see the franc disappear. :)

Yes I imagine, but your country and mine had to give up the franc too, already more than 20 years ago...

Have fun Roland!

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

Some textures...

![textures_eschecs](https://user-images.githubusercontent.com/3421249/72673869-187fd380-3a70-11ea-84d9-b34368349848.png)

Fre;D

**Comment by rchastain** [comment]
Nice!
